#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_QLNV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="doan_QLNV")]
	public partial class QLNVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBangLuong(BangLuong instance);
    partial void UpdateBangLuong(BangLuong instance);
    partial void DeleteBangLuong(BangLuong instance);
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertCTTrinhDo(CTTrinhDo instance);
    partial void UpdateCTTrinhDo(CTTrinhDo instance);
    partial void DeleteCTTrinhDo(CTTrinhDo instance);
    partial void InsertHopDong(HopDong instance);
    partial void UpdateHopDong(HopDong instance);
    partial void DeleteHopDong(HopDong instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertPhanQuyen(PhanQuyen instance);
    partial void UpdatePhanQuyen(PhanQuyen instance);
    partial void DeletePhanQuyen(PhanQuyen instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhongBan(PhongBan instance);
    partial void UpdatePhongBan(PhongBan instance);
    partial void DeletePhongBan(PhongBan instance);
    partial void InsertTrinhDo(TrinhDo instance);
    partial void UpdateTrinhDo(TrinhDo instance);
    partial void DeleteTrinhDo(TrinhDo instance);
    #endregion
		
		public QLNVDataContext() : 
				base(global::doan_QLNV.Properties.Settings.Default.doan_QLNVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLNVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BangLuong> BangLuongs
		{
			get
			{
				return this.GetTable<BangLuong>();
			}
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<CTTrinhDo> CTTrinhDos
		{
			get
			{
				return this.GetTable<CTTrinhDo>();
			}
		}
		
		public System.Data.Linq.Table<HopDong> HopDongs
		{
			get
			{
				return this.GetTable<HopDong>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyen> PhanQuyens
		{
			get
			{
				return this.GetTable<PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<PhongBan> PhongBans
		{
			get
			{
				return this.GetTable<PhongBan>();
			}
		}
		
		public System.Data.Linq.Table<TrinhDo> TrinhDos
		{
			get
			{
				return this.GetTable<TrinhDo>();
			}
		}
		
		public System.Data.Linq.Table<DanhSachPhongBan> DanhSachPhongBans
		{
			get
			{
				return this.GetTable<DanhSachPhongBan>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getPhongBan")]
		public ISingleResult<getPhongBanResult> getPhongBan()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getPhongBanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addPhongBan")]
		public int addPhongBan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenPB", DbType="NVarChar(50)")] string tenPB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenPB);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deletePhongBan")]
		public int deletePhongBan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaPB", DbType="Int")] System.Nullable<int> maPB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maPB);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatePhongBan")]
		public int updatePhongBan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaPB", DbType="Int")] System.Nullable<int> maPB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenPB", DbType="NVarChar(50)")] string tenPB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maPB, tenPB);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap")]
		public ISingleResult<DangNhapResult> DangNhap([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string tk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string mk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tk, mk);
			return ((ISingleResult<DangNhapResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNhanVien")]
		public ISingleResult<getNhanVienResult> getNhanVien()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getNhanVienResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addNhanVien")]
		public int addNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoVaTen", DbType="NVarChar(50)")] string hoVaTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMNV", DbType="NVarChar(10)")] string cMNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(5)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(20)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TonGiao", DbType="NVarChar(20)")] string tonGiao, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="NVarChar(20)")] string sDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ATM", DbType="NVarChar(50)")] string aTM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BHYT", DbType="NVarChar(50)")] string bHYT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenPhong", DbType="NVarChar(50)")] string tenPhong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenCV", DbType="NVarChar(50)")] string tenCV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HopDong", DbType="Int")] System.Nullable<int> hopDong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hoVaTen, cMNV, gioiTinh, ngaySinh, danToc, tonGiao, diaChi, sDT, aTM, bHYT, tenPhong, tenCV, hopDong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateNhanVien")]
		public int updateNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoVaTen", DbType="NVarChar(50)")] string hoVaTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMNV", DbType="NVarChar(10)")] string cMNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(5)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(20)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TonGiao", DbType="NVarChar(20)")] string tonGiao, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="NVarChar(20)")] string sDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ATM", DbType="NVarChar(50)")] string aTM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BHYT", DbType="NVarChar(50)")] string bHYT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenPhong", DbType="NVarChar(50)")] string tenPhong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenCV", DbType="NVarChar(50)")] string tenCV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HopDong", DbType="Int")] System.Nullable<int> hopDong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV, hoVaTen, cMNV, gioiTinh, ngaySinh, danToc, tonGiao, diaChi, sDT, aTM, bHYT, tenPhong, tenCV, hopDong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteNhanVien")]
		public int deleteNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay1NhanVien")]
		public ISingleResult<lay1NhanVienResult> lay1NhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV);
			return ((ISingleResult<lay1NhanVienResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChamCong")]
		public int ChamCong([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DoiMk")]
		public int DoiMk([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string mkcu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string mkmoi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV, mkcu, mkmoi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addChucVu")]
		public int addChucVu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenCV", DbType="NVarChar(50)")] string tenCV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhuCap", DbType="Float")] System.Nullable<double> phuCap)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenCV, phuCap);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteChucVu")]
		public int deleteChucVu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCV", DbType="Int")] System.Nullable<int> maCV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getChucVu")]
		public ISingleResult<getChucVuResult> getChucVu()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getChucVuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateChucVu")]
		public int updateChucVu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCV", DbType="Int")] System.Nullable<int> maCV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenCV", DbType="NVarChar(50)")] string tenCV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhuCap", DbType="Float")] System.Nullable<double> phuCap)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCV, tenCV, phuCap);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addBangLuong")]
		public int addBangLuong([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LuongCB", DbType="Float")] System.Nullable<double> luongCB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoNgayTangCa", DbType="Int")] System.Nullable<int> soNgayTangCa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LuongTangCa", DbType="Float")] System.Nullable<double> luongTangCa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaoHiem", DbType="Float")] System.Nullable<double> baoHiem)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV, luongCB, soNgayTangCa, luongTangCa, baoHiem);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteBangLuong")]
		public int deleteBangLuong([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getBangLuong")]
		public ISingleResult<getBangLuongResult> getBangLuong()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getBangLuongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateBangLuong")]
		public int updateBangLuong([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LuongCB", DbType="Float")] System.Nullable<double> luongCB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoNgayTangCa", DbType="Int")] System.Nullable<int> soNgayTangCa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LuongTangCa", DbType="Float")] System.Nullable<double> luongTangCa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaoHiem", DbType="Float")] System.Nullable<double> baoHiem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThucLanh", DbType="Float")] System.Nullable<double> thucLanh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV, luongCB, soNgayTangCa, luongTangCa, baoHiem, thucLanh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addChuyenCongTac")]
		public int addChuyenCongTac([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCVMoi", DbType="Int")] System.Nullable<int> maCVMoi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaPBMoi", DbType="Int")] System.Nullable<int> maPBMoi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV, maCVMoi, maPBMoi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getChuyenCongTac")]
		public ISingleResult<getChuyenCongTacResult> getChuyenCongTac()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getChuyenCongTacResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateChuyenCongTac")]
		public int updateChuyenCongTac([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaChuyen", DbType="Int")] System.Nullable<int> maChuyen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayChuyen", DbType="Date")] System.Nullable<System.DateTime> ngayChuyen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCVCu", DbType="Int")] System.Nullable<int> maCVCu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCVMoi", DbType="Int")] System.Nullable<int> maCVMoi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaPBMoi", DbType="Int")] System.Nullable<int> maPBMoi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maChuyen, ngayChuyen, maNV, maCVCu, maCVMoi, maPBMoi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addCTTrinhDo")]
		public int addCTTrinhDo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChuyenMon", DbType="NVarChar(50)")] string chuyenMon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayCap", DbType="Date")] System.Nullable<System.DateTime> ngayCap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong", DbType="NVarChar(50)")] string truong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV, chuyenMon, ngayCap, truong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteCTTrinhDo")]
		public int deleteCTTrinhDo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCTTrinhDo")]
		public ISingleResult<getCTTrinhDoResult> getCTTrinhDo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getCTTrinhDoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateCTTrinhDo")]
		public int updateCTTrinhDo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="Int")] System.Nullable<int> maNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChuyenMon", DbType="NVarChar(50)")] string chuyenMon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayCap", DbType="Date")] System.Nullable<System.DateTime> ngayCap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong", DbType="NVarChar(50)")] string truong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, maNV, chuyenMon, ngayCap, truong);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangLuong")]
	public partial class BangLuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private System.Nullable<double> _LuongCB;
		
		private System.Nullable<int> _SoNgayTangCa;
		
		private System.Nullable<double> _LuongTangCa;
		
		private System.Nullable<double> _BaoHiem;
		
		private System.Nullable<double> _ThucLanh;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnLuongCBChanging(System.Nullable<double> value);
    partial void OnLuongCBChanged();
    partial void OnSoNgayTangCaChanging(System.Nullable<int> value);
    partial void OnSoNgayTangCaChanged();
    partial void OnLuongTangCaChanging(System.Nullable<double> value);
    partial void OnLuongTangCaChanged();
    partial void OnBaoHiemChanging(System.Nullable<double> value);
    partial void OnBaoHiemChanged();
    partial void OnThucLanhChanging(System.Nullable<double> value);
    partial void OnThucLanhChanged();
    #endregion
		
		public BangLuong()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongCB", DbType="Float")]
		public System.Nullable<double> LuongCB
		{
			get
			{
				return this._LuongCB;
			}
			set
			{
				if ((this._LuongCB != value))
				{
					this.OnLuongCBChanging(value);
					this.SendPropertyChanging();
					this._LuongCB = value;
					this.SendPropertyChanged("LuongCB");
					this.OnLuongCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayTangCa", DbType="Int")]
		public System.Nullable<int> SoNgayTangCa
		{
			get
			{
				return this._SoNgayTangCa;
			}
			set
			{
				if ((this._SoNgayTangCa != value))
				{
					this.OnSoNgayTangCaChanging(value);
					this.SendPropertyChanging();
					this._SoNgayTangCa = value;
					this.SendPropertyChanged("SoNgayTangCa");
					this.OnSoNgayTangCaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongTangCa", DbType="Float")]
		public System.Nullable<double> LuongTangCa
		{
			get
			{
				return this._LuongTangCa;
			}
			set
			{
				if ((this._LuongTangCa != value))
				{
					this.OnLuongTangCaChanging(value);
					this.SendPropertyChanging();
					this._LuongTangCa = value;
					this.SendPropertyChanged("LuongTangCa");
					this.OnLuongTangCaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHiem", DbType="Float")]
		public System.Nullable<double> BaoHiem
		{
			get
			{
				return this._BaoHiem;
			}
			set
			{
				if ((this._BaoHiem != value))
				{
					this.OnBaoHiemChanging(value);
					this.SendPropertyChanging();
					this._BaoHiem = value;
					this.SendPropertyChanged("BaoHiem");
					this.OnBaoHiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThucLanh", DbType="Float")]
		public System.Nullable<double> ThucLanh
		{
			get
			{
				return this._ThucLanh;
			}
			set
			{
				if ((this._ThucLanh != value))
				{
					this.OnThucLanhChanging(value);
					this.SendPropertyChanging();
					this._ThucLanh = value;
					this.SendPropertyChanged("ThucLanh");
					this.OnThucLanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_BangLuong", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.BangLuong = null;
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.BangLuong = this;
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCV;
		
		private string _TenCV;
		
		private System.Nullable<double> _PhuCap;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCVChanging(int value);
    partial void OnMaCVChanged();
    partial void OnTenCVChanging(string value);
    partial void OnTenCVChanged();
    partial void OnPhuCapChanging(System.Nullable<double> value);
    partial void OnPhuCapChanged();
    #endregion
		
		public ChucVu()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCV", DbType="NVarChar(50)")]
		public string TenCV
		{
			get
			{
				return this._TenCV;
			}
			set
			{
				if ((this._TenCV != value))
				{
					this.OnTenCVChanging(value);
					this.SendPropertyChanging();
					this._TenCV = value;
					this.SendPropertyChanged("TenCV");
					this.OnTenCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuCap", DbType="Float")]
		public System.Nullable<double> PhuCap
		{
			get
			{
				return this._PhuCap;
			}
			set
			{
				if ((this._PhuCap != value))
				{
					this.OnPhuCapChanging(value);
					this.SendPropertyChanging();
					this._PhuCap = value;
					this.SendPropertyChanged("PhuCap");
					this.OnPhuCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanVien", Storage="_NhanViens", ThisKey="MaCV", OtherKey="ChucVu")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu1 = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTTrinhDo")]
	public partial class CTTrinhDo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private int _MaNV;
		
		private string _ChuyenMon;
		
		private System.Nullable<System.DateTime> _NgayCap;
		
		private string _Truong;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<TrinhDo> _TrinhDo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnChuyenMonChanging(string value);
    partial void OnChuyenMonChanged();
    partial void OnNgayCapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapChanged();
    partial void OnTruongChanging(string value);
    partial void OnTruongChanged();
    #endregion
		
		public CTTrinhDo()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			this._TrinhDo = default(EntityRef<TrinhDo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._TrinhDo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenMon", DbType="NVarChar(50)")]
		public string ChuyenMon
		{
			get
			{
				return this._ChuyenMon;
			}
			set
			{
				if ((this._ChuyenMon != value))
				{
					this.OnChuyenMonChanging(value);
					this.SendPropertyChanging();
					this._ChuyenMon = value;
					this.SendPropertyChanged("ChuyenMon");
					this.OnChuyenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong", DbType="NVarChar(50)")]
		public string Truong
		{
			get
			{
				return this._Truong;
			}
			set
			{
				if ((this._Truong != value))
				{
					this.OnTruongChanging(value);
					this.SendPropertyChanging();
					this._Truong = value;
					this.SendPropertyChanged("Truong");
					this.OnTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_CTTrinhDo", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.CTTrinhDo = null;
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.CTTrinhDo = this;
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDo_CTTrinhDo", Storage="_TrinhDo", ThisKey="ID", OtherKey="MaTD", IsForeignKey=true)]
		public TrinhDo TrinhDo
		{
			get
			{
				return this._TrinhDo.Entity;
			}
			set
			{
				TrinhDo previousValue = this._TrinhDo.Entity;
				if (((previousValue != value) 
							|| (this._TrinhDo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrinhDo.Entity = null;
						previousValue.CTTrinhDos.Remove(this);
					}
					this._TrinhDo.Entity = value;
					if ((value != null))
					{
						value.CTTrinhDos.Add(this);
						this._ID = value.MaTD;
					}
					else
					{
						this._ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TrinhDo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDong")]
	public partial class HopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHD;
		
		private string _TenHD;
		
		private System.Nullable<System.DateTime> _NgayBD;
		
		private System.Nullable<System.DateTime> _NgayKT;
		
		private System.Nullable<double> _LuongCB;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnTenHDChanging(string value);
    partial void OnTenHDChanged();
    partial void OnNgayBDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBDChanged();
    partial void OnNgayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKTChanged();
    partial void OnLuongCBChanging(System.Nullable<double> value);
    partial void OnLuongCBChanged();
    #endregion
		
		public HopDong()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHD", DbType="NVarChar(50)")]
		public string TenHD
		{
			get
			{
				return this._TenHD;
			}
			set
			{
				if ((this._TenHD != value))
				{
					this.OnTenHDChanging(value);
					this.SendPropertyChanging();
					this._TenHD = value;
					this.SendPropertyChanged("TenHD");
					this.OnTenHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBD", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBD
		{
			get
			{
				return this._NgayBD;
			}
			set
			{
				if ((this._NgayBD != value))
				{
					this.OnNgayBDChanging(value);
					this.SendPropertyChanging();
					this._NgayBD = value;
					this.SendPropertyChanged("NgayBD");
					this.OnNgayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKT", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKT
		{
			get
			{
				return this._NgayKT;
			}
			set
			{
				if ((this._NgayKT != value))
				{
					this.OnNgayKTChanging(value);
					this.SendPropertyChanging();
					this._NgayKT = value;
					this.SendPropertyChanged("NgayKT");
					this.OnNgayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongCB", DbType="Float")]
		public System.Nullable<double> LuongCB
		{
			get
			{
				return this._LuongCB;
			}
			set
			{
				if ((this._LuongCB != value))
				{
					this.OnLuongCBChanging(value);
					this.SendPropertyChanging();
					this._LuongCB = value;
					this.SendPropertyChanged("LuongCB");
					this.OnLuongCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_NhanVien", Storage="_NhanViens", ThisKey="MaHD", OtherKey="HopDong")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.HopDong1 = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.HopDong1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPQ;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private EntitySet<NhanVien> _NhanViens;
		
		private EntityRef<PhanQuyen> _PhanQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPQChanging(int value);
    partial void OnMaPQChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public NguoiDung()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			this._PhanQuyen = default(EntityRef<PhanQuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPQ", DbType="Int NOT NULL")]
		public int MaPQ
		{
			get
			{
				return this._MaPQ;
			}
			set
			{
				if ((this._MaPQ != value))
				{
					if (this._PhanQuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPQChanging(value);
					this.SendPropertyChanging();
					this._MaPQ = value;
					this.SendPropertyChanged("MaPQ");
					this.OnMaPQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_NhanVien", Storage="_NhanViens", ThisKey="TaiKhoan", OtherKey="TaiKhoan")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_NguoiDung", Storage="_PhanQuyen", ThisKey="MaPQ", OtherKey="MaPQ", IsForeignKey=true)]
		public PhanQuyen PhanQuyen
		{
			get
			{
				return this._PhanQuyen.Entity;
			}
			set
			{
				PhanQuyen previousValue = this._PhanQuyen.Entity;
				if (((previousValue != value) 
							|| (this._PhanQuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanQuyen.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._PhanQuyen.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaPQ = value.MaPQ;
					}
					else
					{
						this._MaPQ = default(int);
					}
					this.SendPropertyChanged("PhanQuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyen")]
	public partial class PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPQ;
		
		private string _TenPQ;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPQChanging(int value);
    partial void OnMaPQChanged();
    partial void OnTenPQChanging(string value);
    partial void OnTenPQChanged();
    #endregion
		
		public PhanQuyen()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPQ", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPQ
		{
			get
			{
				return this._MaPQ;
			}
			set
			{
				if ((this._MaPQ != value))
				{
					this.OnMaPQChanging(value);
					this.SendPropertyChanging();
					this._MaPQ = value;
					this.SendPropertyChanged("MaPQ");
					this.OnMaPQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPQ", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenPQ
		{
			get
			{
				return this._TenPQ;
			}
			set
			{
				if ((this._TenPQ != value))
				{
					this.OnTenPQChanging(value);
					this.SendPropertyChanging();
					this._TenPQ = value;
					this.SendPropertyChanged("TenPQ");
					this.OnTenPQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_NguoiDung", Storage="_NguoiDungs", ThisKey="MaPQ", OtherKey="MaPQ")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _HoVaTen;
		
		private string _CMND;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DanToc;
		
		private string _TonGiao;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private int _Phong;
		
		private System.Nullable<int> _NgayLamTrongThang;
		
		private System.Nullable<System.DateTime> _NgayLamGanNhat;
		
		private System.Nullable<System.DateTime> _NgayGiaNhap;
		
		private string _ATM;
		
		private string _BHYT;
		
		private System.Nullable<int> _SoHD;
		
		private System.Nullable<int> _TrangThai;
		
		private System.Nullable<int> _PhongBan;
		
		private System.Nullable<int> _ChucVu;
		
		private System.Nullable<int> _TrinhDo;
		
		private System.Nullable<int> _HopDong;
		
		private string _TaiKhoan;
		
		private EntityRef<BangLuong> _BangLuong;
		
		private EntityRef<CTTrinhDo> _CTTrinhDo;
		
		private EntityRef<ChucVu> _ChucVu1;
		
		private EntityRef<HopDong> _HopDong1;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
		private EntityRef<PhongBan> _PhongBan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnHoVaTenChanging(string value);
    partial void OnHoVaTenChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnTonGiaoChanging(string value);
    partial void OnTonGiaoChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnPhongChanging(int value);
    partial void OnPhongChanged();
    partial void OnNgayLamTrongThangChanging(System.Nullable<int> value);
    partial void OnNgayLamTrongThangChanged();
    partial void OnNgayLamGanNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLamGanNhatChanged();
    partial void OnNgayGiaNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaNhapChanged();
    partial void OnATMChanging(string value);
    partial void OnATMChanged();
    partial void OnBHYTChanging(string value);
    partial void OnBHYTChanged();
    partial void OnSoHDChanging(System.Nullable<int> value);
    partial void OnSoHDChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    partial void OnPhongBanChanging(System.Nullable<int> value);
    partial void OnPhongBanChanged();
    partial void OnChucVuChanging(System.Nullable<int> value);
    partial void OnChucVuChanged();
    partial void OnTrinhDoChanging(System.Nullable<int> value);
    partial void OnTrinhDoChanged();
    partial void OnHopDongChanging(System.Nullable<int> value);
    partial void OnHopDongChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    #endregion
		
		public NhanVien()
		{
			this._BangLuong = default(EntityRef<BangLuong>);
			this._CTTrinhDo = default(EntityRef<CTTrinhDo>);
			this._ChucVu1 = default(EntityRef<ChucVu>);
			this._HopDong1 = default(EntityRef<HopDong>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			this._PhongBan1 = default(EntityRef<PhongBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoVaTen", DbType="NVarChar(50)")]
		public string HoVaTen
		{
			get
			{
				return this._HoVaTen;
			}
			set
			{
				if ((this._HoVaTen != value))
				{
					this.OnHoVaTenChanging(value);
					this.SendPropertyChanging();
					this._HoVaTen = value;
					this.SendPropertyChanged("HoVaTen");
					this.OnHoVaTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(10)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(20)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonGiao", DbType="NVarChar(20)")]
		public string TonGiao
		{
			get
			{
				return this._TonGiao;
			}
			set
			{
				if ((this._TonGiao != value))
				{
					this.OnTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._TonGiao = value;
					this.SendPropertyChanged("TonGiao");
					this.OnTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phong", DbType="Int NOT NULL")]
		public int Phong
		{
			get
			{
				return this._Phong;
			}
			set
			{
				if ((this._Phong != value))
				{
					this.OnPhongChanging(value);
					this.SendPropertyChanging();
					this._Phong = value;
					this.SendPropertyChanged("Phong");
					this.OnPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLamTrongThang", DbType="Int")]
		public System.Nullable<int> NgayLamTrongThang
		{
			get
			{
				return this._NgayLamTrongThang;
			}
			set
			{
				if ((this._NgayLamTrongThang != value))
				{
					this.OnNgayLamTrongThangChanging(value);
					this.SendPropertyChanging();
					this._NgayLamTrongThang = value;
					this.SendPropertyChanged("NgayLamTrongThang");
					this.OnNgayLamTrongThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLamGanNhat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLamGanNhat
		{
			get
			{
				return this._NgayLamGanNhat;
			}
			set
			{
				if ((this._NgayLamGanNhat != value))
				{
					this.OnNgayLamGanNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayLamGanNhat = value;
					this.SendPropertyChanged("NgayLamGanNhat");
					this.OnNgayLamGanNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaNhap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGiaNhap
		{
			get
			{
				return this._NgayGiaNhap;
			}
			set
			{
				if ((this._NgayGiaNhap != value))
				{
					this.OnNgayGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaNhap = value;
					this.SendPropertyChanged("NgayGiaNhap");
					this.OnNgayGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATM", DbType="NVarChar(50)")]
		public string ATM
		{
			get
			{
				return this._ATM;
			}
			set
			{
				if ((this._ATM != value))
				{
					this.OnATMChanging(value);
					this.SendPropertyChanging();
					this._ATM = value;
					this.SendPropertyChanged("ATM");
					this.OnATMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHYT", DbType="NVarChar(50)")]
		public string BHYT
		{
			get
			{
				return this._BHYT;
			}
			set
			{
				if ((this._BHYT != value))
				{
					this.OnBHYTChanging(value);
					this.SendPropertyChanging();
					this._BHYT = value;
					this.SendPropertyChanged("BHYT");
					this.OnBHYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHD", DbType="Int")]
		public System.Nullable<int> SoHD
		{
			get
			{
				return this._SoHD;
			}
			set
			{
				if ((this._SoHD != value))
				{
					this.OnSoHDChanging(value);
					this.SendPropertyChanging();
					this._SoHD = value;
					this.SendPropertyChanged("SoHD");
					this.OnSoHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongBan", DbType="Int")]
		public System.Nullable<int> PhongBan
		{
			get
			{
				return this._PhongBan;
			}
			set
			{
				if ((this._PhongBan != value))
				{
					if (this._PhongBan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhongBanChanging(value);
					this.SendPropertyChanging();
					this._PhongBan = value;
					this.SendPropertyChanged("PhongBan");
					this.OnPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="Int")]
		public System.Nullable<int> ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					if (this._ChucVu1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDo", DbType="Int")]
		public System.Nullable<int> TrinhDo
		{
			get
			{
				return this._TrinhDo;
			}
			set
			{
				if ((this._TrinhDo != value))
				{
					this.OnTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._TrinhDo = value;
					this.SendPropertyChanged("TrinhDo");
					this.OnTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HopDong", DbType="Int")]
		public System.Nullable<int> HopDong
		{
			get
			{
				return this._HopDong;
			}
			set
			{
				if ((this._HopDong != value))
				{
					if (this._HopDong1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHopDongChanging(value);
					this.SendPropertyChanging();
					this._HopDong = value;
					this.SendPropertyChanged("HopDong");
					this.OnHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(20)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_BangLuong", Storage="_BangLuong", ThisKey="MaNV", OtherKey="MaNV", IsUnique=true, IsForeignKey=false)]
		public BangLuong BangLuong
		{
			get
			{
				return this._BangLuong.Entity;
			}
			set
			{
				BangLuong previousValue = this._BangLuong.Entity;
				if (((previousValue != value) 
							|| (this._BangLuong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangLuong.Entity = null;
						previousValue.NhanVien = null;
					}
					this._BangLuong.Entity = value;
					if ((value != null))
					{
						value.NhanVien = this;
					}
					this.SendPropertyChanged("BangLuong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_CTTrinhDo", Storage="_CTTrinhDo", ThisKey="MaNV", OtherKey="MaNV", IsUnique=true, IsForeignKey=false)]
		public CTTrinhDo CTTrinhDo
		{
			get
			{
				return this._CTTrinhDo.Entity;
			}
			set
			{
				CTTrinhDo previousValue = this._CTTrinhDo.Entity;
				if (((previousValue != value) 
							|| (this._CTTrinhDo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CTTrinhDo.Entity = null;
						previousValue.NhanVien = null;
					}
					this._CTTrinhDo.Entity = value;
					if ((value != null))
					{
						value.NhanVien = this;
					}
					this.SendPropertyChanged("CTTrinhDo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanVien", Storage="_ChucVu1", ThisKey="ChucVu", OtherKey="MaCV", IsForeignKey=true)]
		public ChucVu ChucVu1
		{
			get
			{
				return this._ChucVu1.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu1.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu1.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._ChucVu1.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._ChucVu = value.MaCV;
					}
					else
					{
						this._ChucVu = default(Nullable<int>);
					}
					this.SendPropertyChanged("ChucVu1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_NhanVien", Storage="_HopDong1", ThisKey="HopDong", OtherKey="MaHD", IsForeignKey=true)]
		public HopDong HopDong1
		{
			get
			{
				return this._HopDong1.Entity;
			}
			set
			{
				HopDong previousValue = this._HopDong1.Entity;
				if (((previousValue != value) 
							|| (this._HopDong1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDong1.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._HopDong1.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._HopDong = value.MaHD;
					}
					else
					{
						this._HopDong = default(Nullable<int>);
					}
					this.SendPropertyChanged("HopDong1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_NhanVien", Storage="_NguoiDung", ThisKey="TaiKhoan", OtherKey="TaiKhoan", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._TaiKhoan = value.TaiKhoan;
					}
					else
					{
						this._TaiKhoan = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_NhanVien", Storage="_PhongBan1", ThisKey="PhongBan", OtherKey="MaPB", IsForeignKey=true)]
		public PhongBan PhongBan1
		{
			get
			{
				return this._PhongBan1.Entity;
			}
			set
			{
				PhongBan previousValue = this._PhongBan1.Entity;
				if (((previousValue != value) 
							|| (this._PhongBan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongBan1.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._PhongBan1.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._PhongBan = value.MaPB;
					}
					else
					{
						this._PhongBan = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhongBan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongBan")]
	public partial class PhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPB;
		
		private string _TenPB;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPBChanging(int value);
    partial void OnMaPBChanged();
    partial void OnTenPBChanging(string value);
    partial void OnTenPBChanged();
    #endregion
		
		public PhongBan()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPB", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPB
		{
			get
			{
				return this._MaPB;
			}
			set
			{
				if ((this._MaPB != value))
				{
					this.OnMaPBChanging(value);
					this.SendPropertyChanging();
					this._MaPB = value;
					this.SendPropertyChanged("MaPB");
					this.OnMaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPB", DbType="NVarChar(50)")]
		public string TenPB
		{
			get
			{
				return this._TenPB;
			}
			set
			{
				if ((this._TenPB != value))
				{
					this.OnTenPBChanging(value);
					this.SendPropertyChanging();
					this._TenPB = value;
					this.SendPropertyChanged("TenPB");
					this.OnTenPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_NhanVien", Storage="_NhanViens", ThisKey="MaPB", OtherKey="PhongBan")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan1 = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrinhDo")]
	public partial class TrinhDo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTD;
		
		private string _TenTD;
		
		private EntitySet<CTTrinhDo> _CTTrinhDos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTDChanging(int value);
    partial void OnMaTDChanged();
    partial void OnTenTDChanging(string value);
    partial void OnTenTDChanged();
    #endregion
		
		public TrinhDo()
		{
			this._CTTrinhDos = new EntitySet<CTTrinhDo>(new Action<CTTrinhDo>(this.attach_CTTrinhDos), new Action<CTTrinhDo>(this.detach_CTTrinhDos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTD
		{
			get
			{
				return this._MaTD;
			}
			set
			{
				if ((this._MaTD != value))
				{
					this.OnMaTDChanging(value);
					this.SendPropertyChanging();
					this._MaTD = value;
					this.SendPropertyChanged("MaTD");
					this.OnMaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTD", DbType="NVarChar(50)")]
		public string TenTD
		{
			get
			{
				return this._TenTD;
			}
			set
			{
				if ((this._TenTD != value))
				{
					this.OnTenTDChanging(value);
					this.SendPropertyChanging();
					this._TenTD = value;
					this.SendPropertyChanged("TenTD");
					this.OnTenTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDo_CTTrinhDo", Storage="_CTTrinhDos", ThisKey="MaTD", OtherKey="ID")]
		public EntitySet<CTTrinhDo> CTTrinhDos
		{
			get
			{
				return this._CTTrinhDos;
			}
			set
			{
				this._CTTrinhDos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTTrinhDos(CTTrinhDo entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDo = this;
		}
		
		private void detach_CTTrinhDos(CTTrinhDo entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachPhongBan")]
	public partial class DanhSachPhongBan
	{
		
		private int _MaPB;
		
		private string _TenPB;
		
		public DanhSachPhongBan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPB", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MaPB
		{
			get
			{
				return this._MaPB;
			}
			set
			{
				if ((this._MaPB != value))
				{
					this._MaPB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPB", DbType="NVarChar(50)")]
		public string TenPB
		{
			get
			{
				return this._TenPB;
			}
			set
			{
				if ((this._TenPB != value))
				{
					this._TenPB = value;
				}
			}
		}
	}
	
	public partial class getPhongBanResult
	{
		
		private int _MaPB;
		
		private string _TenPB;
		
		public getPhongBanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPB", DbType="Int NOT NULL")]
		public int MaPB
		{
			get
			{
				return this._MaPB;
			}
			set
			{
				if ((this._MaPB != value))
				{
					this._MaPB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPB", DbType="NVarChar(50)")]
		public string TenPB
		{
			get
			{
				return this._TenPB;
			}
			set
			{
				if ((this._TenPB != value))
				{
					this._TenPB = value;
				}
			}
		}
	}
	
	public partial class DangNhapResult
	{
		
		private int _MaNV;
		
		private int _MaPQ;
		
		public DangNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPQ", DbType="Int NOT NULL")]
		public int MaPQ
		{
			get
			{
				return this._MaPQ;
			}
			set
			{
				if ((this._MaPQ != value))
				{
					this._MaPQ = value;
				}
			}
		}
	}
	
	public partial class getNhanVienResult
	{
		
		private int _MaNV;
		
		private string _HoVaTen;
		
		private string _CMND;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DanToc;
		
		private string _TonGiao;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private System.Nullable<int> _NgayLamTrongThang;
		
		private System.Nullable<System.DateTime> _NgayLamGanNhat;
		
		private System.Nullable<System.DateTime> _NgayGiaNhap;
		
		private string _ATM;
		
		private string _BHYT;
		
		private string _TenPB;
		
		private string _TenCV;
		
		private System.Nullable<int> _HopDong;
		
		public getNhanVienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoVaTen", DbType="NVarChar(50)")]
		public string HoVaTen
		{
			get
			{
				return this._HoVaTen;
			}
			set
			{
				if ((this._HoVaTen != value))
				{
					this._HoVaTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(10)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this._CMND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(20)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonGiao", DbType="NVarChar(20)")]
		public string TonGiao
		{
			get
			{
				return this._TonGiao;
			}
			set
			{
				if ((this._TonGiao != value))
				{
					this._TonGiao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLamTrongThang", DbType="Int")]
		public System.Nullable<int> NgayLamTrongThang
		{
			get
			{
				return this._NgayLamTrongThang;
			}
			set
			{
				if ((this._NgayLamTrongThang != value))
				{
					this._NgayLamTrongThang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLamGanNhat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLamGanNhat
		{
			get
			{
				return this._NgayLamGanNhat;
			}
			set
			{
				if ((this._NgayLamGanNhat != value))
				{
					this._NgayLamGanNhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaNhap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGiaNhap
		{
			get
			{
				return this._NgayGiaNhap;
			}
			set
			{
				if ((this._NgayGiaNhap != value))
				{
					this._NgayGiaNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATM", DbType="NVarChar(50)")]
		public string ATM
		{
			get
			{
				return this._ATM;
			}
			set
			{
				if ((this._ATM != value))
				{
					this._ATM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHYT", DbType="NVarChar(50)")]
		public string BHYT
		{
			get
			{
				return this._BHYT;
			}
			set
			{
				if ((this._BHYT != value))
				{
					this._BHYT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPB", DbType="NVarChar(50)")]
		public string TenPB
		{
			get
			{
				return this._TenPB;
			}
			set
			{
				if ((this._TenPB != value))
				{
					this._TenPB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCV", DbType="NVarChar(50)")]
		public string TenCV
		{
			get
			{
				return this._TenCV;
			}
			set
			{
				if ((this._TenCV != value))
				{
					this._TenCV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HopDong", DbType="Int")]
		public System.Nullable<int> HopDong
		{
			get
			{
				return this._HopDong;
			}
			set
			{
				if ((this._HopDong != value))
				{
					this._HopDong = value;
				}
			}
		}
	}
	
	public partial class lay1NhanVienResult
	{
		
		private int _MaNV;
		
		private string _HoVaTen;
		
		private string _CMND;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DanToc;
		
		private string _TonGiao;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private System.Nullable<int> _NgayLamTrongThang;
		
		private System.Nullable<System.DateTime> _NgayLamGanNhat;
		
		private System.Nullable<System.DateTime> _NgayGiaNhap;
		
		private string _ATM;
		
		private string _BHYT;
		
		private string _TenPB;
		
		private string _TenCV;
		
		private System.Nullable<int> _HopDong;
		
		public lay1NhanVienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoVaTen", DbType="NVarChar(50)")]
		public string HoVaTen
		{
			get
			{
				return this._HoVaTen;
			}
			set
			{
				if ((this._HoVaTen != value))
				{
					this._HoVaTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(10)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this._CMND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(20)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonGiao", DbType="NVarChar(20)")]
		public string TonGiao
		{
			get
			{
				return this._TonGiao;
			}
			set
			{
				if ((this._TonGiao != value))
				{
					this._TonGiao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLamTrongThang", DbType="Int")]
		public System.Nullable<int> NgayLamTrongThang
		{
			get
			{
				return this._NgayLamTrongThang;
			}
			set
			{
				if ((this._NgayLamTrongThang != value))
				{
					this._NgayLamTrongThang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLamGanNhat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLamGanNhat
		{
			get
			{
				return this._NgayLamGanNhat;
			}
			set
			{
				if ((this._NgayLamGanNhat != value))
				{
					this._NgayLamGanNhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaNhap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGiaNhap
		{
			get
			{
				return this._NgayGiaNhap;
			}
			set
			{
				if ((this._NgayGiaNhap != value))
				{
					this._NgayGiaNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATM", DbType="NVarChar(50)")]
		public string ATM
		{
			get
			{
				return this._ATM;
			}
			set
			{
				if ((this._ATM != value))
				{
					this._ATM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHYT", DbType="NVarChar(50)")]
		public string BHYT
		{
			get
			{
				return this._BHYT;
			}
			set
			{
				if ((this._BHYT != value))
				{
					this._BHYT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPB", DbType="NVarChar(50)")]
		public string TenPB
		{
			get
			{
				return this._TenPB;
			}
			set
			{
				if ((this._TenPB != value))
				{
					this._TenPB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCV", DbType="NVarChar(50)")]
		public string TenCV
		{
			get
			{
				return this._TenCV;
			}
			set
			{
				if ((this._TenCV != value))
				{
					this._TenCV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HopDong", DbType="Int")]
		public System.Nullable<int> HopDong
		{
			get
			{
				return this._HopDong;
			}
			set
			{
				if ((this._HopDong != value))
				{
					this._HopDong = value;
				}
			}
		}
	}
	
	public partial class getChucVuResult
	{
		
		private int _MaCV;
		
		private string _TenCV;
		
		private System.Nullable<double> _PhuCap;
		
		public getChucVuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="Int NOT NULL")]
		public int MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this._MaCV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCV", DbType="NVarChar(50)")]
		public string TenCV
		{
			get
			{
				return this._TenCV;
			}
			set
			{
				if ((this._TenCV != value))
				{
					this._TenCV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuCap", DbType="Float")]
		public System.Nullable<double> PhuCap
		{
			get
			{
				return this._PhuCap;
			}
			set
			{
				if ((this._PhuCap != value))
				{
					this._PhuCap = value;
				}
			}
		}
	}
	
	public partial class getBangLuongResult
	{
		
		private int _MaNV;
		
		private System.Nullable<double> _LuongCB;
		
		private System.Nullable<int> _SoNgayTangCa;
		
		private System.Nullable<double> _LuongTangCa;
		
		private System.Nullable<double> _BaoHiem;
		
		private System.Nullable<double> _ThucLanh;
		
		public getBangLuongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongCB", DbType="Float")]
		public System.Nullable<double> LuongCB
		{
			get
			{
				return this._LuongCB;
			}
			set
			{
				if ((this._LuongCB != value))
				{
					this._LuongCB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayTangCa", DbType="Int")]
		public System.Nullable<int> SoNgayTangCa
		{
			get
			{
				return this._SoNgayTangCa;
			}
			set
			{
				if ((this._SoNgayTangCa != value))
				{
					this._SoNgayTangCa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongTangCa", DbType="Float")]
		public System.Nullable<double> LuongTangCa
		{
			get
			{
				return this._LuongTangCa;
			}
			set
			{
				if ((this._LuongTangCa != value))
				{
					this._LuongTangCa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHiem", DbType="Float")]
		public System.Nullable<double> BaoHiem
		{
			get
			{
				return this._BaoHiem;
			}
			set
			{
				if ((this._BaoHiem != value))
				{
					this._BaoHiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThucLanh", DbType="Float")]
		public System.Nullable<double> ThucLanh
		{
			get
			{
				return this._ThucLanh;
			}
			set
			{
				if ((this._ThucLanh != value))
				{
					this._ThucLanh = value;
				}
			}
		}
	}
	
	public partial class getChuyenCongTacResult
	{
		
		private int _MaChuyen;
		
		private System.Nullable<System.DateTime> _NgayChuyen;
		
		private System.Nullable<int> _MaNV;
		
		private System.Nullable<int> _MaCVCu;
		
		private System.Nullable<int> _MaCVMoi;
		
		private System.Nullable<int> _MaPBMoi;
		
		public getChuyenCongTacResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyen", DbType="Int NOT NULL")]
		public int MaChuyen
		{
			get
			{
				return this._MaChuyen;
			}
			set
			{
				if ((this._MaChuyen != value))
				{
					this._MaChuyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyen", DbType="Date")]
		public System.Nullable<System.DateTime> NgayChuyen
		{
			get
			{
				return this._NgayChuyen;
			}
			set
			{
				if ((this._NgayChuyen != value))
				{
					this._NgayChuyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int")]
		public System.Nullable<int> MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCVCu", DbType="Int")]
		public System.Nullable<int> MaCVCu
		{
			get
			{
				return this._MaCVCu;
			}
			set
			{
				if ((this._MaCVCu != value))
				{
					this._MaCVCu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCVMoi", DbType="Int")]
		public System.Nullable<int> MaCVMoi
		{
			get
			{
				return this._MaCVMoi;
			}
			set
			{
				if ((this._MaCVMoi != value))
				{
					this._MaCVMoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPBMoi", DbType="Int")]
		public System.Nullable<int> MaPBMoi
		{
			get
			{
				return this._MaPBMoi;
			}
			set
			{
				if ((this._MaPBMoi != value))
				{
					this._MaPBMoi = value;
				}
			}
		}
	}
	
	public partial class getCTTrinhDoResult
	{
		
		private System.Nullable<int> _ID;
		
		private int _MaNV;
		
		private string _ChuyenMon;
		
		private System.Nullable<System.DateTime> _NgayCap;
		
		private string _Truong;
		
		public getCTTrinhDoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenMon", DbType="NVarChar(50)")]
		public string ChuyenMon
		{
			get
			{
				return this._ChuyenMon;
			}
			set
			{
				if ((this._ChuyenMon != value))
				{
					this._ChuyenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this._NgayCap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong", DbType="NVarChar(50)")]
		public string Truong
		{
			get
			{
				return this._Truong;
			}
			set
			{
				if ((this._Truong != value))
				{
					this._Truong = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
